# Generated by Django 3.2.8 on 2021-10-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(default='Upcoming', max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(verbose_name='due_date')),
            ],
        ),
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('NEWTASK', 'Newtask'), ('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('RUNNING', 'Running'), ('UNKNOWN', 'Unknown')], default='NEWTASK', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todo.list')),
            ],
        ),
    ]
