# Generated by Django 3.2.8 on 2021-10-18 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='assign_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 7, 23, 36, 846438, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 7, 23, 36, 846438, tzinfo=utc)),
        ),
    ]
