# Generated by Django 3.2.8 on 2021-10-18 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_auto_20211018_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='info',
            field=models.CharField(default='Upcoming', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='assign_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 7, 52, 40, 922126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 7, 52, 40, 922126, tzinfo=utc)),
        ),
    ]
