# Generated by Django 3.2.8 on 2021-10-18 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0006_auto_20211018_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='assign_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 8, 14, 3, 934793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='list',
            name='info',
            field=models.CharField(default=['Upcoming', 'ongoing'], max_length=100),
        ),
    ]
