# Generated by Django 3.2.8 on 2021-10-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0008_auto_20211018_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='assign_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='info',
        ),
    ]
